# Generated by Django 3.0 on 2019-12-06 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0002_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='furniture.Owner'),
        ),
    ]
